### ISSUE TITLE
fails to run under MRI 1.8.7

### ISSUE THREAD

**Issue by javmorin** [scoop/bundle_outdated#1]
Some of us are still running 1.8.7 but we want to keep our gems updated anyway (we're crazy like that). Unfortunately bundle_outdated doesn't seem to work with 1.8.x. I at first suspected that it was a neglected inclusion of rubygems, but that doesn't seem to be it (hence I am submitting this issue rather than a pull request).  Perhaps it is a rubygems version requirement that is not identified?

I can confirm it runs correctly w/ 1.9.2-p180. 

```
$ bundle-outdated 
Finding outdated gems..
/home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:38:in `latest_version': undefined method `latest_version_for' for Gem:Module (NoMethodError)
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:43:in `outdated?'
    from /home/mikej/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
    from /home/mikej/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `find_all'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:76:in `each'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:76:in `find_all'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:76:in `outdated_gems'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:53:in `search!'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/lib/bundle_outdated.rb:3:in `search!'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/gems/bundle_outdated-0.0.1/bin/bundle-outdated:22
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/bin/bundle-outdated:19:in `load'
    from /home/mikej/.rvm/gems/ruby-1.8.7-p302/bin/bundle-outdated:19
```

**Comment by scoop** [comment]
Hey Mike,

yeah, it's indeed more of a problem with the version of RubyGems that I fail to detect. Some of the API I'm using is only available on newer releases (I _think_ it's 1.6.0 and newer). I've actually been using it mostly on MRI 1.8.7 projects myself.

I'll get that patched up and submitted hopefully later today.

Thanks for the catch!

Best,  
Patrick
